-- Run this once in the Supabase SQL editor (Project Settings > SQL Editor > New query)
--
-- Adds a journal/audit trail for changes to stock_on_hand. Every "Upload
-- Inventory Count" or "Inventory Adjustment" creates one inventory_journal
-- row (the entry: when, what kind, an optional note) and one or more
-- inventory_journal_lines rows (the archived before/after value for each
-- part+project that changed).

create table inventory_journal (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  entry_type text not null check (entry_type in ('count', 'adjustment')),
  note text
);

create table inventory_journal_lines (
  id bigint generated by default as identity primary key,
  journal_id bigint not null references inventory_journal(id) on delete cascade,
  project_id bigint not null references projects(id),
  part_gcs_id integer not null references parts(gcs_id),
  previous_quantity integer,
  new_quantity integer not null
);

alter table inventory_journal enable row level security;
alter table inventory_journal_lines enable row level security;

-- Permissive policies matching the rest of this project's tables, so the
-- publishable/anon key can read and write.
create policy "Allow public read" on inventory_journal
  for select using (true);
create policy "Allow public insert" on inventory_journal
  for insert with check (true);

create policy "Allow public read" on inventory_journal_lines
  for select using (true);
create policy "Allow public insert" on inventory_journal_lines
  for insert with check (true);
