-- Run this once in the Supabase SQL editor (Project Settings > SQL Editor > New query)
--
-- An Entity (the "projects" table) can be a single physical site, or — like
-- Firelight Solar LP — a legal company that covers many individual rooftop
-- sites. Those individual sites only matter for Purchase Requests (spares
-- inventory stays tracked at the Entity level, unchanged), so this adds a
-- child "sub_projects" table under each Entity, plus a link column on
-- purchase_requests recording which one (if any) a given PO is for.

create table if not exists sub_projects (
  id bigint generated by default as identity primary key,
  project_id bigint not null references projects(id),
  name text not null
);

alter table purchase_requests add column if not exists sub_project_id bigint references sub_projects(id);
