-- Run this once in the Supabase SQL editor for your project
-- (Project Settings > SQL Editor > New query)
--
-- NOTE: a "parts" table already existed in this project but was confirmed
-- empty (0 rows) via the REST API before this drop, so no data is lost.

drop table if exists parts cascade;

create table parts (
  gcs_id integer generated by default as identity primary key,
  gcs_part_id text not null,
  manufacturer_part_number text,
  manufacturer text,
  spare_category text,
  description text,
  primary_location text,
  common_spare_part boolean not null default false,
  max_stock integer,
  min_stock integer,
  created_at timestamptz not null default now()
);

alter table parts enable row level security;

-- Permissive policies for now (matches the "dogs" table setup) so the
-- publishable/anon key can read and write during development.
-- Tighten these (e.g. require auth) before this is a real multi-user system.
create policy "Allow public read" on parts
  for select using (true);

create policy "Allow public insert" on parts
  for insert with check (true);

create policy "Allow public update" on parts
  for update using (true);

create policy "Allow public delete" on parts
  for delete using (true);
