// Builds a TEST COPY of the inventory database that you can load into a second, empty Supabase project.
//
//   node scripts/build_test_database.mjs "<sheet .xlsm>" "<app export .csv>" [outDir]
//
// Writes (default outDir: build/test_copy):
//   1_schema.sql      the whole schema, replayed from supabase/*.sql in a working order, plus the
//                     security scripts you've already run in production
//   2_seed.sql        test data: the parts master list, the entities, each entity's Required Inventory
//                     list and CURRENT stock (taken from your app export), vendors, and two test logins
//   TEST_LOGINS.txt   the test accounts' emails and passwords (for the test project only)
//   README.txt        the steps
//
// What this is not: an exact clone of production. It reproduces what's in the repo's schema files
// plus the one known gap (project_parts.shared). Anything changed by hand in the Supabase dashboard
// (for example the fn_apply_* functions) isn't here. For an exact clone, restore a backup into a new
// project instead.

import { createRequire } from 'node:module'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { loadPartsMaster } from './lib/opening_data.mjs'

const require = createRequire(import.meta.url)
const Papa = require('papaparse')
const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(here, '..')

const [xlsxPath, csvPath, outArg] = process.argv.slice(2)
if (!xlsxPath || !csvPath) {
  console.error('Usage: node scripts/build_test_database.mjs "<sheet .xlsm>" "<app export .csv>" [outDir]')
  process.exit(1)
}
const outDir = outArg || path.join(root, 'build', 'test_copy')
mkdirSync(outDir, { recursive: true })

const order = JSON.parse(readFileSync(path.join(here, 'test_copy_order.json'), 'utf8'))
const sqlDir = path.join(root, 'supabase')
const q = (s) => `'${String(s).replace(/'/g, "''")}'`
const lit = (v) => (v === null || v === undefined ? 'null' : typeof v === 'boolean' ? String(v) : typeof v === 'number' ? String(v) : q(v))

// ---------------- 1_schema.sql ----------------
let schema = `-- TEST COPY, part 1 of 2: schema. Generated by scripts/build_test_database.mjs.
-- Run in the SQL editor of a NEW, EMPTY Supabase project (never production).\n\n`
const addFile = (f) => { schema += `\n-- ===================================================================\n-- ${f}\n-- ===================================================================\n${readFileSync(path.join(sqlDir, f), 'utf8')}\n` }
for (const f of order.files) addFile(f)
schema += `\n-- ===================================================================\n-- Differences between the schema files and production\n-- ===================================================================\n${order.driftFixes}\n`
for (const f of order.afterFiles) addFile(f)
writeFileSync(path.join(outDir, '1_schema.sql'), schema)

// ---------------- 2_seed.sql ----------------
const parsed = Papa.parse(readFileSync(csvPath, 'utf8'), { header: true, skipEmptyLines: true })
const fields = parsed.meta.fields || []
const fm = Object.fromEntries(fields.map((f) => [f.toLowerCase().replace(/[^a-z0-9]/g, ''), f]))
const gcsKey = fm.gcspn || fm.gcsid, entKey = fm.entity || fm.project, qtyKey = fm.quantity || fm.qty
if (!gcsKey || !entKey || !qtyKey) throw new Error('The CSV needs GCS P/N, Entity and Quantity columns')
const stock = parsed.data
  .map((r) => ({ gcs: parseInt(r[gcsKey], 10), entity: String(r[entKey]).trim(), qty: parseInt(r[qtyKey], 10) }))
  .filter((r) => !Number.isNaN(r.gcs) && !Number.isNaN(r.qty) && r.entity)
const entities = [...new Set(stock.map((s) => s.entity))].sort()

// parts: the sheet's master data, plus a placeholder for any P/N that's in the app but not the sheet
const master = loadPartsMaster(xlsxPath)
const have = new Set(master.map((p) => p.gcs_id))
const placeholders = [...new Set(stock.map((s) => s.gcs))].filter((g) => !have.has(g)).sort((a, b) => a - b)
for (const g of placeholders) master.push({ gcs_id: g, gcs_part_id: `TEST-${g}`, manufacturer_part_number: null, manufacturer: null, spare_category: null, description: `Placeholder for P/N ${g} (in the app, not in the sheet)`, primary_location: null, common_spare_part: false, max_stock: null, min_stock: null })

const chunk = (a, n) => Array.from({ length: Math.ceil(a.length / n) }, (_, i) => a.slice(i * n, i * n + n))
const pw = () => crypto.randomBytes(12).toString('base64url')
const logins = [
  { email: 'test.admin@example.com', password: pw(), name: 'Test Admin', roles: ['admin', 'inventory', 'ticketing', 'purchase_req', 'purchase_rec_approval', 'po_issue', 'invoice_matching', 'invoice_approval', 'payment', 'vendor_approval'], note: 'every role' },
  { email: 'test.limited@example.com', password: pw(), name: 'Test Limited', roles: ['purchase_req'], note: 'Purchase Rec only (to check that role limits hold)' },
]

let seed = `-- TEST COPY, part 2 of 2: test data. Generated by scripts/build_test_database.mjs.
-- Run AFTER 1_schema.sql, in the same new project. Stock numbers are your app's CURRENT numbers.\n
-- Parts (sheet master data)
${chunk(master, 100).map((c) => `insert into public.parts (gcs_id, gcs_part_id, manufacturer_part_number, manufacturer, spare_category, description, primary_location, common_spare_part, max_stock, min_stock) overriding system value values\n${c.map((p) => `  (${[p.gcs_id, p.gcs_part_id ?? `TEST-${p.gcs_id}`, p.manufacturer_part_number, p.manufacturer, p.spare_category, p.description, p.primary_location, p.common_spare_part, p.max_stock, p.min_stock].map(lit).join(', ')})`).join(',\n')}\non conflict (gcs_id) do nothing;`).join('\n')}
select setval(pg_get_serial_sequence('public.parts', 'gcs_id'), (select max(gcs_id) from public.parts));

-- Entities (the migrations already add some; the rest come from your export)
insert into public.projects (name) values ${entities.map((e) => `(${q(e)})`).join(', ')} on conflict (name) do nothing;
update public.projects set project_code = lpad(id::text, 2, '0') where project_code is null;

-- Each entity's Required Inventory list = the part/entity pairs in your export; stock = its quantities
create temp table _stock (gcs integer, entity text, qty integer) on commit drop;
${chunk(stock, 400).map((c) => `insert into _stock values\n${c.map((s) => `  (${s.gcs}, ${q(s.entity)}, ${s.qty})`).join(',\n')};`).join('\n')}
insert into public.project_parts (project_id, part_gcs_id)
  select p.id, s.gcs from _stock s join public.projects p on p.name = s.entity
  where exists (select 1 from public.parts x where x.gcs_id = s.gcs)
  on conflict (project_id, part_gcs_id) do nothing;
insert into public.stock_on_hand (project_id, part_gcs_id, quantity)
  select p.id, s.gcs, s.qty from _stock s join public.projects p on p.name = s.entity
  where exists (select 1 from public.parts x where x.gcs_id = s.gcs)
  on conflict (project_id, part_gcs_id) do update set quantity = excluded.quantity;

-- A couple of approved vendors to test purchase orders with
insert into public.vendors (name, contact_name, email, approval_status) values
  ('Test Vendor A', 'Pat Example', 'vendor.a@example.com', 'approved'),
  ('Test Vendor B', 'Sam Example', 'vendor.b@example.com', 'approved')
on conflict (name) do nothing;

-- Test logins (see TEST_LOGINS.txt). Same way the real auth migration creates accounts.
do $$
declare new_id uuid;
begin
${logins.map((u) => `  new_id := gen_random_uuid();
  insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin, confirmation_token, recovery_token, email_change_token_new, email_change)
    values ('00000000-0000-0000-0000-000000000000', new_id, 'authenticated', 'authenticated', ${q(u.email)}, crypt(${q(u.password)}, gen_salt('bf')), now(), now(), now(), '{"provider":"email","providers":["email"]}', '{}', false, '', '', '', '');
  insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    values (gen_random_uuid(), new_id::text, new_id, jsonb_build_object('sub', new_id::text, 'email', ${q(u.email)}), 'email', now(), now(), now());
  insert into public.users (name, display_name, roles, active, auth_user_id, activated_at)
    values (${q(u.email)}, ${q(u.name)}, array[${u.roles.map(q).join(', ')}], true, new_id, now());`).join('\n')}
end $$;
`
writeFileSync(path.join(outDir, '2_seed.sql'), seed)

writeFileSync(path.join(outDir, 'TEST_LOGINS.txt'), `Test logins for the TEST project only. Never use these in production.\n\n${logins.map((u) => `${u.email}\n  password: ${u.password}\n  roles: ${u.roles.join(', ')} (${u.note})`).join('\n\n')}\n`)

writeFileSync(path.join(outDir, 'README.txt'), `HOW TO USE THIS TEST COPY

1. In Supabase, create a NEW project (not production). Give it any name, e.g. "inventory-test".
2. In that project: SQL Editor -> paste the whole of 1_schema.sql -> Run. Then paste 2_seed.sql -> Run.
   (If a run fails, note the error text and the file; the position is shown. Nothing here touches production.)
3. Project Settings -> API: copy the Project URL and the anon public key.
4. In the Inventory repo, create a file named .env.local containing:
      VITE_SUPABASE_URL=<the test Project URL>
      VITE_SUPABASE_KEY=<the test anon key>
   (The same two names your .env already uses, pointed at the test project.)
5. Authentication -> Sign In / Providers: turn OFF "Allow new users to sign up". It is not needed.
6. Run the app against it:   npm run dev     and sign in with a login from TEST_LOGINS.txt.
7. To try the new feature on the test copy, run in the test project's SQL editor, in order:
      supabase/ownership_location_01_schema.sql
      (the generated opening import:  node scripts/build_opening_import.mjs "<sheet>"  -> supabase/ownership_location_02_opening_import.sql)
   Then check it with:  select * from public.fn_check_stock_invariants();   (must return no rows)
Everything here can be thrown away by deleting the test project.
`)

console.log(`Wrote ${outDir}`)
console.log(`  1_schema.sql (${(schema.length / 1024).toFixed(0)} KB, ${order.files.length + order.afterFiles.length} files), 2_seed.sql (${(seed.length / 1024).toFixed(0)} KB)`)
console.log(`  ${master.length} parts (${placeholders.length} placeholders for P/Ns not in the sheet: ${placeholders.join(', ') || 'none'})`)
console.log(`  ${entities.length} entities: ${entities.join(', ')}`)
console.log(`  ${stock.length} part/entity rows of stock`)
console.log('  Test logins written to TEST_LOGINS.txt')
