// Builds the opening-balance import for the Ownership / Physical Location change.
//
//   node scripts/build_opening_import.mjs "<path to .xlsm>" [out.sql]
//
// Reads the OPS - GM SPARE PART LIST sheet:
//   * ownership   = each site block's STOCK ON HAND column
//   * location    = the PRIMARY LOCATION column, by these rules:
//        ON SITE        every owner's units sit on that owner's own site
//        STORAGE...     every owner's units sit in Storage ("STORAGE (CAMBRIDGE)" too)
//        a site name    units sit on that site, but only the entity that owns that site may
//                       hold them there -- anything else needs an entry in
//                       opening_import_config.json -> overrides
//   * overrides   = per-part decisions (see the config file)
// It stops with a list of every row it can't place instead of guessing.
//
// Writes a SQL file (default: supabase/ownership_location_02_opening_import.sql) and prints a
// summary. Nothing here touches a database.

import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadOpeningData } from './lib/opening_data.mjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const xlsxPath = process.argv[2]
const outPath = process.argv[3] || path.join(here, '..', 'supabase', 'ownership_location_02_opening_import.sql')
if (!xlsxPath) {
  console.error('Usage: node scripts/build_opening_import.mjs "<path to .xlsm>" [out.sql]')
  process.exit(1)
}
const data = loadOpeningData(xlsxPath, (problems) =>
  console.error('Cannot build the import. Rows that need a decision:\n  - ' + problems.join('\n  - '))
)
if (!data) process.exit(2)
const { config, ownerRows, finalLoc, notes } = data

const sqlStr = (s) => `'${String(s).replace(/'/g, "''")}'`
const chunk = (arr, n) => Array.from({ length: Math.ceil(arr.length / n) }, (_, i) => arr.slice(i * n, i * n + n))

let sql = `-- Ownership and Physical Location, part 2 of 3: opening balances.
-- GENERATED by scripts/build_opening_import.mjs from "${config.sheet}" (sheet dated ${config.sheetDate}). Do not edit by hand;
-- change opening_import_config.json and regenerate.
--
-- Run AFTER ownership_location_01_schema.sql, on a TEST COPY first. It REPLACES ownership with the sheet's
-- numbers: any entity/part not in the sheet ends at 0. It first copies the current stock_on_hand to
-- public.stock_on_hand_pre_import (only the first time), and records every change in History as one
-- "opening" entry. It aborts, changing nothing, if an entity name can't be matched to exactly one entity,
-- a part isn't in the Master List, or ownership and locations don't add up.

begin;

create temp table _site_map (site text primary key, patterns text[] not null) on commit drop;
insert into _site_map (site, patterns) values
${Object.entries(config.sites).filter(([s]) => !(config.skipSites || []).includes(s)).map(([s, p]) => `  (${sqlStr(s)}, array[${p.map(sqlStr).join(', ')}])`).join(',\n')};

create temp table _proj on commit drop as
  select m.site, array(select p.id from public.projects p where p.name ilike any (m.patterns) order by p.id) as ids
  from _site_map m;

do $$
declare r record;
begin
  for r in select site, ids from _proj where coalesce(cardinality(ids), 0) <> 1 loop
    raise exception 'Entity mapping failed for sheet site "%": matched % entities (%). Fix opening_import_config.json -> sites.',
      r.site, coalesce(cardinality(r.ids), 0), r.ids;
  end loop;
end $$;

create temp table _owner (site text not null, gcs integer not null, qty integer not null) on commit drop;
${chunk(ownerRows, 400).map((c) => `insert into _owner (site, gcs, qty) values\n${c.map((o) => `  (${sqlStr(o.site)}, ${o.gcs}, ${o.qty})`).join(',\n')};`).join('\n')}

create temp table _loc (location text not null, site text, gcs integer not null, qty integer not null) on commit drop;
${chunk(finalLoc, 400).map((c) => `insert into _loc (location, site, gcs, qty) values\n${c.map((l) => `  (${sqlStr(l.location)}, ${l.site ? sqlStr(l.site) : 'null'}, ${l.gcs}, ${l.qty})`).join(',\n')};`).join('\n')}

do $$
declare missing integer[]; jid bigint; n_before integer; n_changed integer; n_new_pp integer;
begin
  select array_agg(distinct o.gcs order by o.gcs) into missing
  from _owner o where not exists (select 1 from public.parts p where p.gcs_id = o.gcs);
  if missing is not null then
    raise exception 'These P/Ns are in the sheet but not in the Master List: %', missing;
  end if;

  -- one-time safety copy of the current ownership numbers
  if to_regclass('public.stock_on_hand_pre_import') is null then
    create table public.stock_on_hand_pre_import as table public.stock_on_hand;
  end if;

  -- every owner has to carry the part on its Required Inventory list
  insert into public.project_parts (project_id, part_gcs_id)
  select distinct pm.ids[1], o.gcs from _owner o join _proj pm using (site)
  on conflict (project_id, part_gcs_id) do nothing;
  get diagnostics n_new_pp = row_count;

  insert into public.inventory_journal (entry_type, note)
  values ('opening', 'Opening balances from "${config.sheet}" (${config.sheetDate}): ownership replaced with the sheet''s stock on hand, locations set from Primary Location')
  returning id into jid;

  -- history: every ownership change, old value -> sheet value
  insert into public.inventory_journal_lines (journal_id, project_id, part_gcs_id, previous_quantity, new_quantity)
  select jid, coalesce(n.pid, e.project_id), coalesce(n.gcs, e.part_gcs_id), coalesce(e.quantity, 0), coalesce(n.qty, 0)
  from (select pm.ids[1] as pid, o.gcs, o.qty from _owner o join _proj pm using (site)) n
  full join public.stock_on_hand e on e.project_id = n.pid and e.part_gcs_id = n.gcs
  where coalesce(e.quantity, 0) <> coalesce(n.qty, 0);
  get diagnostics n_changed = row_count;

  -- replace ownership
  update public.stock_on_hand set quantity = 0, updated_at = now();
  insert into public.stock_on_hand (project_id, part_gcs_id, quantity)
  select pm.ids[1], o.gcs, o.qty from _owner o join _proj pm using (site)
  on conflict (project_id, part_gcs_id) do update set quantity = excluded.quantity, updated_at = now();

  -- replace locations
  delete from public.stock_location;
  insert into public.stock_location (part_gcs_id, location, project_id, quantity)
  select l.gcs, l.location, case when l.location = 'site' then pm.ids[1] end, l.qty
  from _loc l left join _proj pm on pm.site = l.site;

  insert into public.inventory_journal_lines (journal_id, part_gcs_id, location, location_project_id, previous_location_qty, new_location_qty)
  select jid, sl.part_gcs_id, sl.location, sl.project_id, 0, sl.quantity from public.stock_location sl;

  -- the rules must hold for every part, or none of this is applied
  perform inv_private.assert_part_ok(g) from (select distinct part_gcs_id as g from public.stock_on_hand union select distinct part_gcs_id from public.stock_location) x;

  raise notice 'opening import ok: % ownership changes recorded, % Required Inventory rows added', n_changed, n_new_pp;
end $$;

commit;
`

writeFileSync(outPath, sql)

// ---- summary
const bySite = {}
for (const o of ownerRows) bySite[o.site] = (bySite[o.site] || 0) + o.qty
const byLoc = { storage: 0, barn: 0, site: 0 }
for (const l of finalLoc) byLoc[l.location] += l.qty
const parts = new Set(ownerRows.map((o) => o.gcs))
console.log(`Wrote ${outPath}`)
console.log(`${parts.size} parts with stock, ${ownerRows.length} ownership rows, ${finalLoc.length} location rows`)
console.log('Ownership by site:', JSON.stringify(bySite))
console.log('Units by location type:', JSON.stringify(byLoc))
console.log('Overrides applied:'); for (const n of notes) console.log('  ' + n)
